"""Added Restaurant model

Revision ID: 87975efcb357
Revises: 0c7fde184e72
Create Date: 2021-12-21 13:09:52.649858

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "87975efcb357"
down_revision = "0c7fde184e72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurants",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=350), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("address", sa.String(length=120), nullable=True),
        sa.Column("webpage", sa.String(length=50), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=True),
        sa.Column(
            "avg_rating", sa.Numeric(precision=2, scale=1), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_restaurants_country"),
        "restaurants",
        ["country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_restaurants_postal_code"),
        "restaurants",
        ["postal_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_restaurants_postal_code"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_country"), table_name="restaurants")
    op.drop_table("restaurants")
    # ### end Alembic commands ###
